### ISSUE TITLE
Support filtered handlers

### ISSUE THREAD

**Issue by jwilm** [jwilm/chatbot#6]
You generally don't want the bot to interject every time you say `ping` in a channel. Add a feature where handlers are either unfiltered or filtered by requiring the bot be addressed. For example:

**Unfiltered**

``` yml
you: I say ping and the bot responds always
bot: pong
```

**Filtered**

``` yml
you: When I say ping the bot doesn't respond.. until it's directly addressed
# silence
you: bot ping
bot: pong
```
