### ISSUE TITLE
Add a countdown handler

### ISSUE THREAD

**Issue by jwilm** [jwilm/chatbot#9]
Create a handler where a countdown can be registered and queried. Example:

``` yml
you: bot create a countdown named rust 1.0 expiring on may 15 2015
bot: got it! registered "rust 1.0" countdown for May 15, 2015.

you: bot how long until rust 1.0
bot: 10 days until rust 1.0
```

This is blocked on [a brain](https://github.com/jwilm/chatbot/issues/7) and [direct address filtering](https://github.com/jwilm/chatbot/issues/6).
